daaset_id: NF-ToN-IoT-v3
raw_path: data/raw/NF-ToN-IoT-v3.csv
non_numerical_columns:
- IPV4_SRC_ADDR
- IPV4_DST_ADDR
features_to_exclude: null
label_column: Attack
benign_label: Benign
label_classes:
- Benign
- scanning
- xss
- ddos
- password
- dos
- injection
- backdoor
- mitm
- ransomware
autoencoder:
  latent_dim: 25
  hidden_dims:
  - 44
  - 39
  epochs: 50
  batch_size: 512
  dropout: 0.0377
  regularization: 0.0019
dataset_invariants:
  all:
    has_duplicates: true
    has_missing_numeric: false
    n_rows: 27520260
    n_cols: 55
  without_confounders:
    has_duplicates: true
    has_missing_numeric: false
    n_rows: 27520260
    n_cols: 55
