daaset_id: NF-ToN-IoT-v3

raw_path: "data/raw/NF-ToN-IoT-v3.csv"

non_numerical_columns:
  - "IPV4_SRC_ADDR"
  - "IPV4_DST_ADDR"

features_to_exclude:

label_column: "Attack"

benign_label: "Benign"

label_classes:
  - "Benign"
  - "scanning"
  - "xss"
  - "ddos"
  - "password"
  - "dos"
  - "injection"
  - "backdoor"
  - "mitm"
  - "ransomware"

autoencoder:
  latent_dim: 25
  hidden_dims: [44, 39]
  epochs: 10
  batch_size: 512
  dropout: 0.0377
  regularization: 0.0019
